"""
Constants here
"""

# ------------------------COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
BLACK_HIGHLIGHT = (0, 0, 0, 150)

# ------------------------BUTTON SIZE
BUTTON_WIDTH = 220
BUTTON_HEIGHT = 60

# ------------------------SCENE SIZES
T_SCREEN_WIDTH = 800
T_SCREEN_HEIGHT = 600

G_SCREEN_WIDTH = 1280
G_SCREEN_HEIGHT = 720

S_SCREEN_WIDTH = 1280
S_SCREEN_HEIGHT = 720

# ------------------------SOUNDS
HOVER_SOUND = "blipshort1.wav"

# ------------------------PYMUNK
EARTH_GRAVITY = 0, -980
TERRAIN_THICKNESS = 3
TERRAIN_FRICTION = 1.
SEGMENT_LENGTH = 75

ANTI_SPACECRAFT_WHEEL_SIZE = 15
ANTI_SPACECRAFT_MOVE_FORCE = 35
DEFAULT_FORCE = (0, 0)
DEFAULT_MOMENT = 1
DEFAULT_MASS = 1
DEFAULT_FRICTION = .5

